AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda function triggered by S3 event

Resources:
  SyncRepo:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: scripts/
      Handler: sync_repo.lambda_handler
      Runtime: python3.10
      MemorySize: 128
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        S3Event:
          Type: S3
          Properties:
            Bucket: !Ref RepoBucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: pipelines/
  RepoBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: lb-gh2gl
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: LambdaS3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                Resource: arn:aws:s3:::lb-gh2gl/*
        - PolicyName: LambdaLogs
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:DescribeLogStreams
                  - xray:PutTraceSegments
                  - xray:PutTelemetryRecords
                  - xray:GetSamplingRules
                  - xray:GetSamplingTargets
                  - xray:GetSamplingStatisticSummaries
                  - xray:BatchGetTraces
                  - xray:GetServiceGraph
                  - xray:GetTraceGraph
                  - xray:GetTraceSummaries
                  - xray:PutTelemetryRecords
                Resource: !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*