name: Send repository to S3

on:
  push:
    branches: [ togitlab ]
  pull_request:
    branches: [ togitlab ]

env:
  AWS_REGION : "ap-southeast-1"
  BUCKET: "lb-gh2gl"

permissions:
      id-token: write
      contents: read
jobs:
  UploadToS3:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::767398122165:role/GitHubAction-AssumeRoleWithAction
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}
      - name: tar and upload to S3
        run: |
          files=$(ls)
          repo=$(echo ${{ github.repository }} | cut -d'/' -f2)
          tar -czvf  ${repo}.tar.gz ${files} .github
          aws s3 cp ${repo}.tar.gz s3://${BUCKET}/pipelines/${repo}.tar.gz
          aws s3 cp MANIFEST.json s3://${BUCKET}/manifests/${repo}.json
