name: Send repository to S3

on:
  push:
    branches: [ togitlab ]
  pull_request:
    branches: [ togitlab ]

env:
  AWS_REGION : "ap-southeast-1"
  BUCKET: "lb-gh2gl"

permissions:
      id-token: write
      contents: read
jobs:
  AssumeRoleAndCallIdentity:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::767398122165:role/GitHubAction-AssumeRoleWithAction
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}
      - name: get repo
        uses: actions/checkout@v2
      - name: tar and upload to S3
        run: |
          repoTar=$(echo ${{ github.repository }} | cut -d'/' -f2).tar.gz
          tar -czvf --exclude='.git*' ${repoTar} .
          aws s3 cp ${repoTar} s3://${BUCKET}/pipelines/${repoTar}
